on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: build to backend
    runs-on: ubuntu-18.04
    
    steps: 
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
