on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: build to backend
    runs-on: ubuntu-latest
    
    steps: 
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '19'
      - name: Setup git
        run: |
          git config --local user.email ""
          git config --local user.name "GitHub Action"
      - name: Clone Admin
        run: git clone https://github.com/TeamCoderX/joinstu-admin-vue.git
      - name: Setup Admin
        working-directory: ./joinstu-admin-vue
        run: |
          npm install
          npm run build
      - name: Copy to backend
        run: |
          git config --global credential.credentialStore dpapi 
          git clone -b deploy --single-branch https://Team-coderX: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@github.com/TeamCoderX/joinstu-backend.git
          rm -rf joinstu-backend/dist/admin
          mkdir joinstu-backend/dist/admin
          cp -r ./joinstu-admin-vue/dist/* joinstu-backend/dist/admin
      - name: Commit files
        working-directory: ./joinstu-backend
        run: |
          git commit -m "Add changes" -a
          git push
        

